### OPTIONAL CONFIGURATION FILE FOR MINEMANAGER
### THIS WILL OVERWRITE DEFAULTS, EDIT WITH CAUTION

# World configuration
WORLD_NAME="mc-server"

# Server memory resources
INITIAL_MEMORY="1024M"
MAXIMUM_MEMORY="4096M"

# Service configuration
mcServerUser="minecraft"
mcServiceName="minecraft_server"

### DIRECTORIES
# Main server directory
serviceDir="/opt/minecraft"
# Server directories
serverDir="${serviceDir}/server"
serverFile="${serverDir}/server.jar"
javaDir="${serviceDir}/java"
worldDir="${serviceDir}/world"
logFile="${javaDir}/logs/latest.log"

### JAVA
# Java binary path (multi-version environments)
JAVA_BIN="/usr/bin/java"